// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package Protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRequest_RequestType int32

const (
	MessageRequest_AUTH_REQUEST     MessageRequest_RequestType = 0
	MessageRequest_C2CSEND_REQUEST  MessageRequest_RequestType = 1
	MessageRequest_C2CPUSH_REQUEST  MessageRequest_RequestType = 2
	MessageRequest_C2GSEND_REQUEST  MessageRequest_RequestType = 3
	MessageRequest_C2GPUSH_REQUEST  MessageRequest_RequestType = 4
	MessageRequest_CtrlSEND_REQUEST MessageRequest_RequestType = 5
	MessageRequest_CtrPUSH_REQUEST  MessageRequest_RequestType = 6
	MessageRequest_KICKOUT_REQUEST  MessageRequest_RequestType = 7
	MessageRequest_PULL_REQUEST     MessageRequest_RequestType = 8
	MessageRequest_CONTROL_REQUEST  MessageRequest_RequestType = 9
)

var MessageRequest_RequestType_name = map[int32]string{
	0: "AUTH_REQUEST",
	1: "C2CSEND_REQUEST",
	2: "C2CPUSH_REQUEST",
	3: "C2GSEND_REQUEST",
	4: "C2GPUSH_REQUEST",
	5: "CtrlSEND_REQUEST",
	6: "CtrPUSH_REQUEST",
	7: "KICKOUT_REQUEST",
	8: "PULL_REQUEST",
	9: "CONTROL_REQUEST",
}

var MessageRequest_RequestType_value = map[string]int32{
	"AUTH_REQUEST":     0,
	"C2CSEND_REQUEST":  1,
	"C2CPUSH_REQUEST":  2,
	"C2GSEND_REQUEST":  3,
	"C2GPUSH_REQUEST":  4,
	"CtrlSEND_REQUEST": 5,
	"CtrPUSH_REQUEST":  6,
	"KICKOUT_REQUEST":  7,
	"PULL_REQUEST":     8,
	"CONTROL_REQUEST":  9,
}

func (x MessageRequest_RequestType) String() string {
	return proto.EnumName(MessageRequest_RequestType_name, int32(x))
}

func (MessageRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0}
}

type MessageRequest_CtrlType int32

const (
	MessageRequest_CREATE_GROUP     MessageRequest_CtrlType = 0
	MessageRequest_GROUP_ADDMEMBERS MessageRequest_CtrlType = 1
	MessageRequest_GROUP_EXIT       MessageRequest_CtrlType = 3
	MessageRequest_GROUP_DELETE     MessageRequest_CtrlType = 4
	MessageRequest_MSG_BACK         MessageRequest_CtrlType = 5
)

var MessageRequest_CtrlType_name = map[int32]string{
	0: "CREATE_GROUP",
	1: "GROUP_ADDMEMBERS",
	3: "GROUP_EXIT",
	4: "GROUP_DELETE",
	5: "MSG_BACK",
}

var MessageRequest_CtrlType_value = map[string]int32{
	"CREATE_GROUP":     0,
	"GROUP_ADDMEMBERS": 1,
	"GROUP_EXIT":       3,
	"GROUP_DELETE":     4,
	"MSG_BACK":         5,
}

func (x MessageRequest_CtrlType) String() string {
	return proto.EnumName(MessageRequest_CtrlType_name, int32(x))
}

func (MessageRequest_CtrlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 1}
}

type MessageRequest_Reasion int32

const (
	MessageRequest_OTHER_LOGIN MessageRequest_Reasion = 0
)

var MessageRequest_Reasion_name = map[int32]string{
	0: "OTHER_LOGIN",
}

var MessageRequest_Reasion_value = map[string]int32{
	"OTHER_LOGIN": 0,
}

func (x MessageRequest_Reasion) String() string {
	return proto.EnumName(MessageRequest_Reasion_name, int32(x))
}

func (MessageRequest_Reasion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 2}
}

type MessageResponse_Status int32

const (
	MessageResponse_OK  MessageResponse_Status = 0
	MessageResponse_Err MessageResponse_Status = 1
)

var MessageResponse_Status_name = map[int32]string{
	0: "OK",
	1: "Err",
}

var MessageResponse_Status_value = map[string]int32{
	"OK":  0,
	"Err": 1,
}

func (x MessageResponse_Status) String() string {
	return proto.EnumName(MessageResponse_Status_name, int32(x))
}

func (MessageResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2, 0}
}

type MessageResponse_ResponseType int32

const (
	MessageResponse_Auth_ACK_RESPONSE     MessageResponse_ResponseType = 0
	MessageResponse_C2CSEND_ACK_RESPONSE  MessageResponse_ResponseType = 1
	MessageResponse_C2GSEND_ACK_RESPONSE  MessageResponse_ResponseType = 2
	MessageResponse_CtrlSEND_ACK_RESPONSE MessageResponse_ResponseType = 3
	MessageResponse_C2CPUSH_RESPONSE      MessageResponse_ResponseType = 4
	MessageResponse_C2GPUSH_RESPONSE      MessageResponse_ResponseType = 5
	MessageResponse_CtrlPUSH_RESPONSE     MessageResponse_ResponseType = 6
	MessageResponse_PULL_RESPONSE         MessageResponse_ResponseType = 7
)

var MessageResponse_ResponseType_name = map[int32]string{
	0: "Auth_ACK_RESPONSE",
	1: "C2CSEND_ACK_RESPONSE",
	2: "C2GSEND_ACK_RESPONSE",
	3: "CtrlSEND_ACK_RESPONSE",
	4: "C2CPUSH_RESPONSE",
	5: "C2GPUSH_RESPONSE",
	6: "CtrlPUSH_RESPONSE",
	7: "PULL_RESPONSE",
}

var MessageResponse_ResponseType_value = map[string]int32{
	"Auth_ACK_RESPONSE":     0,
	"C2CSEND_ACK_RESPONSE":  1,
	"C2GSEND_ACK_RESPONSE":  2,
	"CtrlSEND_ACK_RESPONSE": 3,
	"C2CPUSH_RESPONSE":      4,
	"C2GPUSH_RESPONSE":      5,
	"CtrlPUSH_RESPONSE":     6,
	"PULL_RESPONSE":         7,
}

func (x MessageResponse_ResponseType) String() string {
	return proto.EnumName(MessageResponse_ResponseType_name, int32(x))
}

func (MessageResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2, 1}
}

type MessageRequest struct {
	TypeOfMsg            MessageRequest_RequestType `protobuf:"varint,1,opt,name=TypeOfMsg,proto3,enum=Protocol.MessageRequest_RequestType" json:"TypeOfMsg,omitempty"`
	From                 int64                      `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64                      `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Group                int64                      `protobuf:"varint,4,opt,name=group,proto3" json:"group,omitempty"`
	Content              string                     `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Uid                  int64                      `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Msgid                int64                      `protobuf:"varint,7,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Token                string                     `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	Timestamp            int64                      `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TypeOfCtrl           MessageRequest_CtrlType    `protobuf:"varint,10,opt,name=TypeOfCtrl,proto3,enum=Protocol.MessageRequest_CtrlType" json:"TypeOfCtrl,omitempty"`
	Reasion              MessageRequest_Reasion     `protobuf:"varint,11,opt,name=reasion,proto3,enum=Protocol.MessageRequest_Reasion" json:"reasion,omitempty"`
	Offset               int64                      `protobuf:"varint,12,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32                      `protobuf:"varint,13,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetTypeOfMsg() MessageRequest_RequestType {
	if m != nil {
		return m.TypeOfMsg
	}
	return MessageRequest_AUTH_REQUEST
}

func (m *MessageRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *MessageRequest) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *MessageRequest) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *MessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MessageRequest) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *MessageRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MessageRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageRequest) GetTypeOfCtrl() MessageRequest_CtrlType {
	if m != nil {
		return m.TypeOfCtrl
	}
	return MessageRequest_CREATE_GROUP
}

func (m *MessageRequest) GetReasion() MessageRequest_Reasion {
	if m != nil {
		return m.Reasion
	}
	return MessageRequest_OTHER_LOGIN
}

func (m *MessageRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MessageRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PullMsg struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Group                int64    `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Msgid                int64    `protobuf:"varint,5,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Cmdid                int32    `protobuf:"varint,6,opt,name=cmdid,proto3" json:"cmdid,omitempty"`
	SendTime             int64    `protobuf:"varint,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMsg) Reset()         { *m = PullMsg{} }
func (m *PullMsg) String() string { return proto.CompactTextString(m) }
func (*PullMsg) ProtoMessage()    {}
func (*PullMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *PullMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMsg.Unmarshal(m, b)
}
func (m *PullMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMsg.Marshal(b, m, deterministic)
}
func (m *PullMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMsg.Merge(m, src)
}
func (m *PullMsg) XXX_Size() int {
	return xxx_messageInfo_PullMsg.Size(m)
}
func (m *PullMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PullMsg proto.InternalMessageInfo

func (m *PullMsg) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *PullMsg) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *PullMsg) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *PullMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PullMsg) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *PullMsg) GetCmdid() int32 {
	if m != nil {
		return m.Cmdid
	}
	return 0
}

func (m *PullMsg) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type MessageResponse struct {
	TypeOfResponse       MessageResponse_ResponseType `protobuf:"varint,1,opt,name=TypeOfResponse,proto3,enum=Protocol.MessageResponse_ResponseType" json:"TypeOfResponse,omitempty"`
	Msgid                int64                        `protobuf:"varint,2,opt,name=msgid,proto3" json:"msgid,omitempty"`
	MsgTo                int64                        `protobuf:"varint,3,opt,name=msg_to,json=msgTo,proto3" json:"msg_to,omitempty"`
	MsgFrom              int64                        `protobuf:"varint,4,opt,name=msg_from,json=msgFrom,proto3" json:"msg_from,omitempty"`
	MsgGroup             int64                        `protobuf:"varint,5,opt,name=msg_group,json=msgGroup,proto3" json:"msg_group,omitempty"`
	Content              string                       `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64                        `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status               MessageResponse_Status       `protobuf:"varint,8,opt,name=status,proto3,enum=Protocol.MessageResponse_Status" json:"status,omitempty"`
	ErrCode              int32                        `protobuf:"varint,9,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string                       `protobuf:"bytes,10,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Msglist              []*PullMsg                   `protobuf:"bytes,11,rep,name=msglist,proto3" json:"msglist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetTypeOfResponse() MessageResponse_ResponseType {
	if m != nil {
		return m.TypeOfResponse
	}
	return MessageResponse_Auth_ACK_RESPONSE
}

func (m *MessageResponse) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *MessageResponse) GetMsgTo() int64 {
	if m != nil {
		return m.MsgTo
	}
	return 0
}

func (m *MessageResponse) GetMsgFrom() int64 {
	if m != nil {
		return m.MsgFrom
	}
	return 0
}

func (m *MessageResponse) GetMsgGroup() int64 {
	if m != nil {
		return m.MsgGroup
	}
	return 0
}

func (m *MessageResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageResponse) GetStatus() MessageResponse_Status {
	if m != nil {
		return m.Status
	}
	return MessageResponse_OK
}

func (m *MessageResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MessageResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *MessageResponse) GetMsglist() []*PullMsg {
	if m != nil {
		return m.Msglist
	}
	return nil
}

type ACKResponse struct {
	Msgid                int64    `protobuf:"varint,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACKResponse) Reset()         { *m = ACKResponse{} }
func (m *ACKResponse) String() string { return proto.CompactTextString(m) }
func (*ACKResponse) ProtoMessage()    {}
func (*ACKResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *ACKResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACKResponse.Unmarshal(m, b)
}
func (m *ACKResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACKResponse.Marshal(b, m, deterministic)
}
func (m *ACKResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACKResponse.Merge(m, src)
}
func (m *ACKResponse) XXX_Size() int {
	return xxx_messageInfo_ACKResponse.Size(m)
}
func (m *ACKResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ACKResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ACKResponse proto.InternalMessageInfo

func (m *ACKResponse) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *ACKResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("Protocol.MessageRequest_RequestType", MessageRequest_RequestType_name, MessageRequest_RequestType_value)
	proto.RegisterEnum("Protocol.MessageRequest_CtrlType", MessageRequest_CtrlType_name, MessageRequest_CtrlType_value)
	proto.RegisterEnum("Protocol.MessageRequest_Reasion", MessageRequest_Reasion_name, MessageRequest_Reasion_value)
	proto.RegisterEnum("Protocol.MessageResponse_Status", MessageResponse_Status_name, MessageResponse_Status_value)
	proto.RegisterEnum("Protocol.MessageResponse_ResponseType", MessageResponse_ResponseType_name, MessageResponse_ResponseType_value)
	proto.RegisterType((*MessageRequest)(nil), "Protocol.MessageRequest")
	proto.RegisterType((*PullMsg)(nil), "Protocol.PullMsg")
	proto.RegisterType((*MessageResponse)(nil), "Protocol.MessageResponse")
	proto.RegisterType((*ACKResponse)(nil), "Protocol.ACKResponse")
	proto.RegisterType((*EmptyRequest)(nil), "Protocol.EmptyRequest")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 861 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcd, 0x6e, 0xea, 0x46,
	0x14, 0xc6, 0x06, 0xdb, 0x70, 0xe0, 0x12, 0x67, 0x9a, 0xdc, 0x3a, 0xb9, 0x5d, 0x50, 0xab, 0xaa,
	0x90, 0x2a, 0xa1, 0x2a, 0xdd, 0x54, 0x55, 0x37, 0x8e, 0xe3, 0x72, 0x23, 0x02, 0xa6, 0x63, 0x23,
	0x75, 0x67, 0x71, 0xc3, 0x84, 0xa2, 0x62, 0x86, 0x7a, 0x86, 0x4a, 0x77, 0xd9, 0x17, 0xe8, 0xaa,
	0xcf, 0xd0, 0x87, 0xe9, 0x23, 0xf4, 0x69, 0xaa, 0xf9, 0xc1, 0x60, 0x92, 0xdc, 0x15, 0xe7, 0x7c,
	0xf3, 0x1d, 0xfb, 0x9c, 0xe3, 0xef, 0x1b, 0xa0, 0xbb, 0x2d, 0x28, 0xa7, 0x8f, 0x74, 0x3d, 0x90,
	0x01, 0x6a, 0x4e, 0x75, 0xee, 0xff, 0x65, 0x43, 0x77, 0x4c, 0x18, 0x9b, 0x2f, 0x09, 0x26, 0xbf,
	0xef, 0x08, 0xe3, 0xe8, 0x16, 0x5a, 0xe9, 0xc7, 0x2d, 0x89, 0x9f, 0xc6, 0x6c, 0xe9, 0x19, 0x3d,
	0xa3, 0xdf, 0xbd, 0xf9, 0x6a, 0xb0, 0x2f, 0x18, 0x54, 0xc9, 0x03, 0xfd, 0x2b, 0x0a, 0xf0, 0xa1,
	0x0c, 0x21, 0x68, 0x3c, 0x15, 0x34, 0xf7, 0xcc, 0x9e, 0xd1, 0xaf, 0x63, 0x19, 0xa3, 0x2e, 0x98,
	0x9c, 0x7a, 0x75, 0x89, 0x98, 0x9c, 0xa2, 0x0b, 0xb0, 0x96, 0x05, 0xdd, 0x6d, 0xbd, 0x86, 0x84,
	0x54, 0x82, 0x3c, 0x70, 0x1e, 0xe9, 0x86, 0x93, 0x0d, 0xf7, 0xac, 0x9e, 0xd1, 0x6f, 0xe1, 0x7d,
	0x8a, 0x5c, 0xa8, 0xef, 0x56, 0x0b, 0xcf, 0x96, 0x6c, 0x11, 0x8a, 0x27, 0xe4, 0x6c, 0xb9, 0x5a,
	0x78, 0x8e, 0x7a, 0x82, 0x4c, 0x04, 0xca, 0xe9, 0x6f, 0x64, 0xe3, 0x35, 0x65, 0xbd, 0x4a, 0xd0,
	0x17, 0xd0, 0xe2, 0xab, 0x9c, 0x30, 0x3e, 0xcf, 0xb7, 0x5e, 0x4b, 0xf2, 0x0f, 0x00, 0x0a, 0x00,
	0x54, 0xf3, 0x21, 0x2f, 0xd6, 0x1e, 0xc8, 0xa1, 0xbf, 0x7c, 0x75, 0x68, 0x41, 0x92, 0x13, 0x1f,
	0x15, 0xa1, 0x1f, 0xc0, 0x29, 0xc8, 0x9c, 0xad, 0xe8, 0xc6, 0x6b, 0xcb, 0xfa, 0xde, 0x27, 0x96,
	0x26, 0x79, 0x78, 0x5f, 0x80, 0xde, 0x82, 0x4d, 0x9f, 0x9e, 0x18, 0xe1, 0x5e, 0x47, 0x76, 0xa6,
	0x33, 0x31, 0xca, 0x7a, 0x95, 0xaf, 0xb8, 0xf7, 0xa6, 0x67, 0xf4, 0x2d, 0xac, 0x12, 0xff, 0x3f,
	0x03, 0xda, 0x47, 0x7b, 0x47, 0x2e, 0x74, 0x82, 0x59, 0xfa, 0x3e, 0xc3, 0xd1, 0xcf, 0xb3, 0x28,
	0x49, 0xdd, 0x1a, 0xfa, 0x0c, 0xce, 0xc2, 0x9b, 0x30, 0x89, 0x26, 0x77, 0x25, 0x68, 0x68, 0x70,
	0x3a, 0x4b, 0x0e, 0x4c, 0x53, 0x81, 0xc3, 0x0a, 0xb3, 0xae, 0xc1, 0x0a, 0xb3, 0x81, 0x2e, 0xc0,
	0x15, 0x73, 0x56, 0xa8, 0x96, 0xa4, 0xf2, 0xa2, 0x42, 0xb5, 0x05, 0x38, 0xba, 0x0f, 0x47, 0xf1,
	0x2c, 0x2d, 0x41, 0x47, 0x74, 0x39, 0x9d, 0x3d, 0x3c, 0x94, 0x48, 0x53, 0xd6, 0xc6, 0x93, 0x14,
	0xc7, 0x07, 0xb0, 0xe5, 0x7f, 0x80, 0xe6, 0x7e, 0xbd, 0xa2, 0x24, 0xc4, 0x51, 0x90, 0x46, 0xd9,
	0x10, 0xc7, 0xb3, 0xa9, 0x5b, 0x13, 0x4d, 0xc8, 0x30, 0x0b, 0xee, 0xee, 0xc6, 0xd1, 0xf8, 0x36,
	0xc2, 0x89, 0x6b, 0xa0, 0x2e, 0x80, 0x42, 0xa3, 0x5f, 0xee, 0x45, 0xff, 0x2e, 0x74, 0x54, 0x7e,
	0x17, 0x3d, 0x44, 0x69, 0xe4, 0x36, 0x50, 0x07, 0x9a, 0xe3, 0x64, 0x98, 0xdd, 0x06, 0xe1, 0xc8,
	0xb5, 0xfc, 0x6b, 0x70, 0xf4, 0x27, 0x40, 0x67, 0xd0, 0x8e, 0xd3, 0xf7, 0x11, 0xce, 0x1e, 0xe2,
	0xe1, 0xfd, 0xc4, 0xad, 0xf9, 0xff, 0x18, 0xe0, 0x4c, 0x77, 0xeb, 0xf5, 0xb1, 0x8a, 0x8d, 0x67,
	0x2a, 0x36, 0x9f, 0xab, 0xb8, 0xfe, 0x8a, 0x8a, 0x1b, 0x55, 0x15, 0x97, 0x9a, 0xb5, 0x4e, 0x34,
	0xfb, 0x98, 0x2f, 0xb4, 0xba, 0x2d, 0xac, 0x12, 0xf4, 0x0e, 0x5a, 0x8c, 0x6c, 0x16, 0x99, 0xd0,
	0xa9, 0xd6, 0x78, 0x53, 0x00, 0xe9, 0x2a, 0x27, 0xfe, 0x9f, 0x16, 0x9c, 0x95, 0xba, 0x62, 0x5b,
	0xba, 0x61, 0x04, 0x4d, 0xa0, 0xab, 0x14, 0xb9, 0x47, 0xb4, 0x7f, 0xbf, 0x7e, 0x41, 0x8a, 0x8a,
	0x30, 0xd8, 0x07, 0x52, 0xcf, 0x27, 0xd5, 0x87, 0x66, 0xcd, 0xe3, 0x66, 0x2f, 0xc1, 0xce, 0xd9,
	0x32, 0x2b, 0xcd, 0x2c, 0xe0, 0x94, 0xa2, 0x2b, 0x68, 0x0a, 0x58, 0x6e, 0x4c, 0x59, 0xda, 0xc9,
	0xd9, 0xf2, 0x27, 0xb1, 0xb4, 0x77, 0xd0, 0x12, 0x47, 0x6a, 0x51, 0x6a, 0x70, 0xc1, 0x1d, 0x9e,
	0xee, 0xca, 0xae, 0xee, 0xaa, 0xe2, 0x59, 0xe7, 0xd4, 0xb3, 0xdf, 0x83, 0xcd, 0xf8, 0x9c, 0xef,
	0x98, 0x34, 0xfa, 0xcb, 0x7e, 0xd3, 0x43, 0x26, 0x92, 0x87, 0x35, 0x5f, 0x74, 0x4a, 0x8a, 0x22,
	0x7b, 0xa4, 0x0b, 0x22, 0xaf, 0x02, 0x0b, 0x3b, 0xa4, 0x28, 0x42, 0xba, 0x20, 0xe8, 0x73, 0x10,
	0x61, 0x96, 0xb3, 0xa5, 0xbc, 0x05, 0x5a, 0xd8, 0x26, 0x45, 0x21, 0xb4, 0xf0, 0x0d, 0x88, 0x69,
	0xd6, 0x2b, 0xc6, 0xbd, 0x76, 0xaf, 0xde, 0x6f, 0xdf, 0x9c, 0x1f, 0x5e, 0xa7, 0xf5, 0x82, 0xf7,
	0x0c, 0xff, 0x0a, 0x6c, 0xf5, 0x4a, 0x64, 0x83, 0x19, 0x8f, 0xdc, 0x1a, 0x72, 0xa0, 0x1e, 0x15,
	0x85, 0x6b, 0xf8, 0xff, 0x1a, 0xd0, 0x39, 0xde, 0x39, 0xba, 0x84, 0xf3, 0x60, 0xc7, 0x7f, 0xcd,
	0x82, 0x70, 0x94, 0xe1, 0x28, 0x99, 0xc6, 0x93, 0x24, 0x72, 0x6b, 0xc8, 0x83, 0x8b, 0xbd, 0x85,
	0x2b, 0x27, 0x86, 0x3a, 0x19, 0x3e, 0x3f, 0x31, 0xd1, 0x15, 0x5c, 0x96, 0x16, 0xad, 0x1c, 0xd5,
	0xa5, 0x7b, 0x4b, 0xf3, 0x6b, 0x54, 0x79, 0xba, 0x34, 0xba, 0x46, 0x2d, 0xd1, 0x91, 0x78, 0x4c,
	0x15, 0xb6, 0xd1, 0x39, 0xbc, 0xd1, 0x06, 0xd6, 0x90, 0xe3, 0x07, 0xd0, 0x0e, 0xc2, 0xd1, 0x73,
	0xb9, 0x18, 0xc7, 0x72, 0xa9, 0x7c, 0x45, 0xf3, 0xe4, 0x2b, 0xfa, 0x5d, 0xe8, 0x44, 0xf9, 0x96,
	0x7f, 0xd4, 0x17, 0xda, 0xcd, 0xdf, 0x06, 0xb4, 0x53, 0x9a, 0x90, 0xe2, 0x0f, 0x22, 0xf7, 0xfe,
	0x23, 0x38, 0x09, 0xd9, 0x2c, 0x44, 0xe8, 0xbd, 0x76, 0xa1, 0x5e, 0x5f, 0x1e, 0x4e, 0x8e, 0xfa,
	0xf1, 0x6b, 0x68, 0x08, 0xdd, 0x72, 0xd9, 0x74, 0x38, 0xe7, 0x04, 0xbd, 0x3d, 0x50, 0x8f, 0xdf,
	0x7b, 0x7d, 0xf5, 0xaa, 0x7a, 0xfc, 0xda, 0xb7, 0xc6, 0x07, 0x5b, 0xfe, 0x71, 0x7e, 0xf7, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x02, 0xc1, 0xfe, 0x4a, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToServerMsgClient is the client API for ToServerMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToServerMsgClient interface {
	SendMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*ACKResponse, error)
	ResponseToGate(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (ToServerMsg_ResponseToGateClient, error)
}

type toServerMsgClient struct {
	cc *grpc.ClientConn
}

func NewToServerMsgClient(cc *grpc.ClientConn) ToServerMsgClient {
	return &toServerMsgClient{cc}
}

func (c *toServerMsgClient) SendMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*ACKResponse, error) {
	out := new(ACKResponse)
	err := c.cc.Invoke(ctx, "/Protocol.ToServerMsg/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toServerMsgClient) ResponseToGate(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (ToServerMsg_ResponseToGateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ToServerMsg_serviceDesc.Streams[0], "/Protocol.ToServerMsg/ResponseToGate", opts...)
	if err != nil {
		return nil, err
	}
	x := &toServerMsgResponseToGateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ToServerMsg_ResponseToGateClient interface {
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type toServerMsgResponseToGateClient struct {
	grpc.ClientStream
}

func (x *toServerMsgResponseToGateClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ToServerMsgServer is the server API for ToServerMsg service.
type ToServerMsgServer interface {
	SendMsg(context.Context, *MessageRequest) (*ACKResponse, error)
	ResponseToGate(*EmptyRequest, ToServerMsg_ResponseToGateServer) error
}

func RegisterToServerMsgServer(s *grpc.Server, srv ToServerMsgServer) {
	s.RegisterService(&_ToServerMsg_serviceDesc, srv)
}

func _ToServerMsg_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToServerMsgServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Protocol.ToServerMsg/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToServerMsgServer).SendMsg(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToServerMsg_ResponseToGate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToServerMsgServer).ResponseToGate(m, &toServerMsgResponseToGateServer{stream})
}

type ToServerMsg_ResponseToGateServer interface {
	Send(*MessageResponse) error
	grpc.ServerStream
}

type toServerMsgResponseToGateServer struct {
	grpc.ServerStream
}

func (x *toServerMsgResponseToGateServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ToServerMsg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Protocol.ToServerMsg",
	HandlerType: (*ToServerMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _ToServerMsg_SendMsg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ResponseToGate",
			Handler:       _ToServerMsg_ResponseToGate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol.proto",
}
