// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package Protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthResponse_Status int32

const (
	AuthResponse_OK  AuthResponse_Status = 0
	AuthResponse_Err AuthResponse_Status = 1
)

var AuthResponse_Status_name = map[int32]string{
	0: "OK",
	1: "Err",
}

var AuthResponse_Status_value = map[string]int32{
	"OK":  0,
	"Err": 1,
}

func (x AuthResponse_Status) String() string {
	return proto.EnumName(AuthResponse_Status_name, int32(x))
}

func (AuthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1, 0}
}

type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AuthRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AuthResponse struct {
	Status               AuthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=Protocol.AuthResponse_Status" json:"status,omitempty"`
	ErrCode              int32               `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string              `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetStatus() AuthResponse_Status {
	if m != nil {
		return m.Status
	}
	return AuthResponse_OK
}

func (m *AuthResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *AuthResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("Protocol.AuthResponse_Status", AuthResponse_Status_name, AuthResponse_Status_value)
	proto.RegisterType((*AuthRequest)(nil), "Protocol.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "Protocol.AuthResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x2e, 0xdd, 0x36, 0xa3, 0x48, 0x18, 0x04, 0x53, 0x50, 0x28, 0x39, 0xf5, 0xb4,
	0x07, 0xc5, 0x07, 0x10, 0xf1, 0x24, 0xa2, 0x6c, 0x1f, 0xa0, 0xc4, 0x66, 0x68, 0x8b, 0xa6, 0x1b,
	0x67, 0x66, 0xdf, 0xc4, 0x07, 0x96, 0x6c, 0x14, 0x3d, 0xcd, 0x3f, 0x3f, 0x3f, 0xdf, 0x3f, 0x03,
	0xd0, 0x24, 0xdd, 0xfb, 0x9e, 0xa3, 0x46, 0x9c, 0xbf, 0x0e, 0x63, 0x1b, 0x3f, 0xea, 0x35, 0x9c,
	0xde, 0x27, 0xdd, 0x07, 0xfa, 0x4c, 0x24, 0x8a, 0x17, 0x30, 0xd5, 0xf8, 0x4e, 0xc7, 0xca, 0x2c,
	0xcd, 0xaa, 0x08, 0xe3, 0x82, 0x25, 0xd8, 0x74, 0x68, 0xab, 0x49, 0xf6, 0x06, 0x89, 0x57, 0x50,
	0xe8, 0xa1, 0x23, 0xd1, 0xa6, 0xeb, 0x2b, 0xbb, 0x34, 0x2b, 0x1b, 0xfe, 0x8c, 0xfa, 0xcb, 0xc0,
	0xd9, 0x48, 0x95, 0x3e, 0x1e, 0x85, 0xf0, 0x0e, 0x9c, 0x68, 0xa3, 0x49, 0x32, 0xf7, 0xfc, 0xe6,
	0xda, 0xff, 0x1e, 0xe0, 0xff, 0xe7, 0xfc, 0x3a, 0x87, 0xc2, 0x4f, 0x18, 0x17, 0x30, 0x27, 0xe6,
	0xcd, 0x36, 0xb6, 0x94, 0xcb, 0xa7, 0x61, 0x46, 0xcc, 0x0f, 0xb1, 0x25, 0xbc, 0x84, 0x41, 0x6e,
	0x3a, 0xd9, 0xe5, 0xfa, 0x22, 0x38, 0x62, 0x7e, 0x96, 0x5d, 0xbd, 0x00, 0x37, 0x52, 0xd0, 0xc1,
	0xe4, 0xe5, 0xa9, 0x3c, 0xc1, 0x19, 0xd8, 0x47, 0xe6, 0xd2, 0xbc, 0xb9, 0xfc, 0xfc, 0xed, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x62, 0x6e, 0x1a, 0x0a, 0x01, 0x00, 0x00,
}
