// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2g.proto

package Protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端发送
type C2GSendRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Group                int64    `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GSendRequest) Reset()         { *m = C2GSendRequest{} }
func (m *C2GSendRequest) String() string { return proto.CompactTextString(m) }
func (*C2GSendRequest) ProtoMessage()    {}
func (*C2GSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5148771b948c99, []int{0}
}

func (m *C2GSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GSendRequest.Unmarshal(m, b)
}
func (m *C2GSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GSendRequest.Marshal(b, m, deterministic)
}
func (m *C2GSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GSendRequest.Merge(m, src)
}
func (m *C2GSendRequest) XXX_Size() int {
	return xxx_messageInfo_C2GSendRequest.Size(m)
}
func (m *C2GSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C2GSendRequest proto.InternalMessageInfo

func (m *C2GSendRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *C2GSendRequest) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *C2GSendRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type C2GSendResponse struct {
	Msgid                int64    `protobuf:"varint,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GSendResponse) Reset()         { *m = C2GSendResponse{} }
func (m *C2GSendResponse) String() string { return proto.CompactTextString(m) }
func (*C2GSendResponse) ProtoMessage()    {}
func (*C2GSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5148771b948c99, []int{1}
}

func (m *C2GSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GSendResponse.Unmarshal(m, b)
}
func (m *C2GSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GSendResponse.Marshal(b, m, deterministic)
}
func (m *C2GSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GSendResponse.Merge(m, src)
}
func (m *C2GSendResponse) XXX_Size() int {
	return xxx_messageInfo_C2GSendResponse.Size(m)
}
func (m *C2GSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_C2GSendResponse proto.InternalMessageInfo

func (m *C2GSendResponse) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *C2GSendResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type C2GPushRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Group                int64    `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Msgid                int64    `protobuf:"varint,4,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GPushRequest) Reset()         { *m = C2GPushRequest{} }
func (m *C2GPushRequest) String() string { return proto.CompactTextString(m) }
func (*C2GPushRequest) ProtoMessage()    {}
func (*C2GPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5148771b948c99, []int{2}
}

func (m *C2GPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GPushRequest.Unmarshal(m, b)
}
func (m *C2GPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GPushRequest.Marshal(b, m, deterministic)
}
func (m *C2GPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GPushRequest.Merge(m, src)
}
func (m *C2GPushRequest) XXX_Size() int {
	return xxx_messageInfo_C2GPushRequest.Size(m)
}
func (m *C2GPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C2GPushRequest proto.InternalMessageInfo

func (m *C2GPushRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *C2GPushRequest) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *C2GPushRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *C2GPushRequest) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *C2GPushRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type C2GPushResponse struct {
	Msgid                int64    `protobuf:"varint,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GPushResponse) Reset()         { *m = C2GPushResponse{} }
func (m *C2GPushResponse) String() string { return proto.CompactTextString(m) }
func (*C2GPushResponse) ProtoMessage()    {}
func (*C2GPushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5148771b948c99, []int{3}
}

func (m *C2GPushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GPushResponse.Unmarshal(m, b)
}
func (m *C2GPushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GPushResponse.Marshal(b, m, deterministic)
}
func (m *C2GPushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GPushResponse.Merge(m, src)
}
func (m *C2GPushResponse) XXX_Size() int {
	return xxx_messageInfo_C2GPushResponse.Size(m)
}
func (m *C2GPushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GPushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_C2GPushResponse proto.InternalMessageInfo

func (m *C2GPushResponse) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func init() {
	proto.RegisterType((*C2GSendRequest)(nil), "Protocol.C2GSendRequest")
	proto.RegisterType((*C2GSendResponse)(nil), "Protocol.C2GSendResponse")
	proto.RegisterType((*C2GPushRequest)(nil), "Protocol.C2GPushRequest")
	proto.RegisterType((*C2GPushResponse)(nil), "Protocol.C2GPushResponse")
}

func init() { proto.RegisterFile("c2g.proto", fileDescriptor_4c5148771b948c99) }

var fileDescriptor_4c5148771b948c99 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x36, 0x4a, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x08, 0x00, 0x51, 0xc9, 0xf9, 0x39, 0x4a, 0x21, 0x5c,
	0x7c, 0xce, 0x46, 0xee, 0xc1, 0xa9, 0x79, 0x29, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x42, 0x5c, 0x2c, 0x69, 0x45, 0xf9, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0xb6,
	0x90, 0x08, 0x17, 0x6b, 0x7a, 0x51, 0x7e, 0x69, 0x81, 0x04, 0x13, 0x58, 0x10, 0xc2, 0x11, 0x92,
	0xe0, 0x62, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x71, 0x95, 0x5c, 0xb9, 0xf8, 0xe1, 0xa6, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0x8c,
	0xc8, 0x2d, 0x4e, 0xcf, 0x4c, 0x81, 0x9a, 0x0b, 0xe1, 0x08, 0xc9, 0x70, 0x71, 0x96, 0x64, 0xe6,
	0xa6, 0x16, 0x97, 0x24, 0xe6, 0xc2, 0x0c, 0x47, 0x08, 0x28, 0x75, 0x30, 0x82, 0x5d, 0x17, 0x50,
	0x5a, 0x9c, 0x41, 0x45, 0xd7, 0x21, 0x9c, 0xc2, 0x82, 0xd3, 0x29, 0xac, 0xe8, 0x4e, 0x51, 0x07,
	0xfb, 0x08, 0xe2, 0x12, 0x7c, 0x3e, 0x4a, 0x62, 0x03, 0x87, 0xb0, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0x9c, 0x6d, 0xfc, 0x6e, 0x01, 0x00, 0x00,
}
