// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pack.proto

package Protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pack_PackType int32

const (
	Pack_Auth_Request      Pack_PackType = 0
	Pack_Auth_Response     Pack_PackType = 1
	Pack_C2CSend_Request   Pack_PackType = 2
	Pack_C2CSend_Response  Pack_PackType = 3
	Pack_C2CPush_Request   Pack_PackType = 4
	Pack_C2CPush_Response  Pack_PackType = 5
	Pack_C2GSend_Request   Pack_PackType = 6
	Pack_C2GSend_Response  Pack_PackType = 7
	Pack_C2GPush_Request   Pack_PackType = 8
	Pack_C2GPush_Response  Pack_PackType = 9
	Pack_CtrlSend_Request  Pack_PackType = 10
	Pack_CtrlSend_Response Pack_PackType = 11
	Pack_CtrlPush_Request  Pack_PackType = 12
	Pack_CtrlPush_Response Pack_PackType = 13
	Pack_Kickout_Request   Pack_PackType = 14
	Pack_Pull_Request      Pack_PackType = 15
	Pack_Pull_Msg          Pack_PackType = 16
	Pack_Pull_Response     Pack_PackType = 17
)

var Pack_PackType_name = map[int32]string{
	0:  "Auth_Request",
	1:  "Auth_Response",
	2:  "C2CSend_Request",
	3:  "C2CSend_Response",
	4:  "C2CPush_Request",
	5:  "C2CPush_Response",
	6:  "C2GSend_Request",
	7:  "C2GSend_Response",
	8:  "C2GPush_Request",
	9:  "C2GPush_Response",
	10: "CtrlSend_Request",
	11: "CtrlSend_Response",
	12: "CtrlPush_Request",
	13: "CtrlPush_Response",
	14: "Kickout_Request",
	15: "Pull_Request",
	16: "Pull_Msg",
	17: "Pull_Response",
}

var Pack_PackType_value = map[string]int32{
	"Auth_Request":      0,
	"Auth_Response":     1,
	"C2CSend_Request":   2,
	"C2CSend_Response":  3,
	"C2CPush_Request":   4,
	"C2CPush_Response":  5,
	"C2GSend_Request":   6,
	"C2GSend_Response":  7,
	"C2GPush_Request":   8,
	"C2GPush_Response":  9,
	"CtrlSend_Request":  10,
	"CtrlSend_Response": 11,
	"CtrlPush_Request":  12,
	"CtrlPush_Response": 13,
	"Kickout_Request":   14,
	"Pull_Request":      15,
	"Pull_Msg":          16,
	"Pull_Response":     17,
}

func (x Pack_PackType) String() string {
	return proto.EnumName(Pack_PackType_name, int32(x))
}

func (Pack_PackType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3827fe073a5f7620, []int{0, 0}
}

type Pack struct {
	Type                 Pack_PackType `protobuf:"varint,1,opt,name=type,proto3,enum=Protocol.Pack_PackType" json:"type,omitempty"`
	Body                 string        `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Pack) Reset()         { *m = Pack{} }
func (m *Pack) String() string { return proto.CompactTextString(m) }
func (*Pack) ProtoMessage()    {}
func (*Pack) Descriptor() ([]byte, []int) {
	return fileDescriptor_3827fe073a5f7620, []int{0}
}

func (m *Pack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pack.Unmarshal(m, b)
}
func (m *Pack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pack.Marshal(b, m, deterministic)
}
func (m *Pack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pack.Merge(m, src)
}
func (m *Pack) XXX_Size() int {
	return xxx_messageInfo_Pack.Size(m)
}
func (m *Pack) XXX_DiscardUnknown() {
	xxx_messageInfo_Pack.DiscardUnknown(m)
}

var xxx_messageInfo_Pack proto.InternalMessageInfo

func (m *Pack) GetType() Pack_PackType {
	if m != nil {
		return m.Type
	}
	return Pack_Auth_Request
}

func (m *Pack) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("Protocol.Pack_PackType", Pack_PackType_name, Pack_PackType_value)
	proto.RegisterType((*Pack)(nil), "Protocol.Pack")
}

func init() { proto.RegisterFile("pack.proto", fileDescriptor_3827fe073a5f7620) }

var fileDescriptor_3827fe073a5f7620 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd1, 0x41, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0x71, 0x37, 0x26, 0x8e, 0xd7, 0x01, 0xdd, 0xab, 0x46, 0x8e, 0x84, 0x13, 0x89, 0xc9,
	0x0e, 0xf8, 0x09, 0x0c, 0x07, 0x0e, 0xc6, 0x64, 0x99, 0xde, 0x0d, 0x8c, 0x46, 0xcd, 0x16, 0x5a,
	0x69, 0x7b, 0xd8, 0x27, 0xf4, 0x53, 0x99, 0x98, 0x96, 0xb7, 0xc3, 0x5e, 0x60, 0x79, 0xfa, 0xcb,
	0x3f, 0x4b, 0x07, 0x20, 0xb7, 0x75, 0x53, 0xc8, 0xa3, 0xd0, 0x02, 0xd3, 0xd2, 0xfe, 0xd5, 0xa2,
	0x5d, 0xfc, 0x0c, 0x20, 0x29, 0xb7, 0x75, 0x83, 0x0f, 0x90, 0xe8, 0x4e, 0xf2, 0x59, 0x34, 0x8f,
	0x96, 0x93, 0xd5, 0x7d, 0xe1, 0x45, 0x61, 0x4f, 0xdd, 0xcf, 0x5b, 0x27, 0x79, 0xe5, 0x10, 0x22,
	0x24, 0x3b, 0xb1, 0xef, 0x66, 0xf1, 0x3c, 0x5a, 0x8e, 0x2a, 0xf7, 0xbc, 0xf8, 0x8d, 0x21, 0xf5,
	0x0c, 0x19, 0x64, 0x4f, 0x46, 0x7f, 0xbe, 0x57, 0xfc, 0xdb, 0x70, 0xa5, 0xd9, 0x05, 0xe6, 0x30,
	0xa6, 0x45, 0x49, 0x71, 0x50, 0x9c, 0x45, 0x78, 0x03, 0xd3, 0xf5, 0x6a, 0xfd, 0xca, 0x0f, 0xfb,
	0xde, 0xc5, 0x78, 0x0b, 0xec, 0x3c, 0x12, 0x1d, 0x10, 0x2d, 0x8d, 0x3a, 0x27, 0x13, 0xa2, 0x34,
	0x12, 0xbd, 0x3c, 0xd1, 0x4d, 0x50, 0x1d, 0x9e, 0xe8, 0x26, 0xac, 0x5e, 0x11, 0x0d, 0xaa, 0x29,
	0xd1, 0xb0, 0x3a, 0x72, 0xab, 0x3e, 0xb6, 0x41, 0x16, 0xf0, 0x0e, 0xf2, 0x7f, 0x2b, 0xe1, 0x6b,
	0x8f, 0x83, 0x70, 0xe6, 0x71, 0x58, 0x1e, 0xdb, 0x97, 0x78, 0xfe, 0xaa, 0x1b, 0x61, 0x74, 0x6f,
	0x27, 0xf6, 0xfe, 0x4a, 0xd3, 0xb6, 0xfd, 0x32, 0xc5, 0x0c, 0x52, 0xb7, 0xbc, 0xa8, 0x0f, 0xc6,
	0xec, 0x6d, 0xd2, 0x39, 0x75, 0xf2, 0xdd, 0xd0, 0x7d, 0xda, 0xc7, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0xfe, 0xac, 0xee, 0xe8, 0x01, 0x00, 0x00,
}
