// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pull.proto

package Protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13fb7c35cd38c13, []int{0}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PullRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PullRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PullMsg struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Group                int64    `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Msgid                int64    `protobuf:"varint,4,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Cmdid                int32    `protobuf:"varint,5,opt,name=cmdid,proto3" json:"cmdid,omitempty"`
	SendTime             int64    `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMsg) Reset()         { *m = PullMsg{} }
func (m *PullMsg) String() string { return proto.CompactTextString(m) }
func (*PullMsg) ProtoMessage()    {}
func (*PullMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13fb7c35cd38c13, []int{1}
}

func (m *PullMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMsg.Unmarshal(m, b)
}
func (m *PullMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMsg.Marshal(b, m, deterministic)
}
func (m *PullMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMsg.Merge(m, src)
}
func (m *PullMsg) XXX_Size() int {
	return xxx_messageInfo_PullMsg.Size(m)
}
func (m *PullMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PullMsg proto.InternalMessageInfo

func (m *PullMsg) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *PullMsg) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *PullMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PullMsg) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *PullMsg) GetCmdid() int32 {
	if m != nil {
		return m.Cmdid
	}
	return 0
}

func (m *PullMsg) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type PullResponse struct {
	Msg                  []*PullMsg `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13fb7c35cd38c13, []int{2}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetMsg() []*PullMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*PullRequest)(nil), "Protocol.PullRequest")
	proto.RegisterType((*PullMsg)(nil), "Protocol.PullMsg")
	proto.RegisterType((*PullResponse)(nil), "Protocol.PullResponse")
}

func init() { proto.RegisterFile("pull.proto", fileDescriptor_e13fb7c35cd38c13) }

var fileDescriptor_e13fb7c35cd38c13 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x41, 0x6b, 0xc4, 0x20,
	0x10, 0x85, 0xb1, 0x6e, 0xb2, 0xbb, 0xb3, 0x3d, 0xb4, 0x43, 0x29, 0x42, 0x2f, 0x21, 0xbd, 0xe4,
	0x94, 0x43, 0xf7, 0x77, 0x2c, 0x2c, 0xd2, 0x7b, 0xa1, 0xd1, 0x04, 0x41, 0x63, 0x1a, 0xf5, 0xaf,
	0xf4, 0xf7, 0x2e, 0xa3, 0xc9, 0xc9, 0xf9, 0x9e, 0xcf, 0xa7, 0x3e, 0x80, 0x25, 0x59, 0xdb, 0x2f,
	0xab, 0x8f, 0x1e, 0x4f, 0x77, 0x5a, 0x06, 0x6f, 0xdb, 0x1b, 0x5c, 0xee, 0xc9, 0x5a, 0xa9, 0xff,
	0x92, 0x0e, 0x11, 0x5f, 0x80, 0x27, 0xa3, 0x04, 0x6b, 0x58, 0xc7, 0x25, 0x8d, 0xf8, 0x0e, 0xb5,
	0x1f, 0xc7, 0xa0, 0xa3, 0x78, 0xca, 0xe2, 0x46, 0xf8, 0x06, 0x95, 0x35, 0xce, 0x44, 0xc1, 0x1b,
	0xd6, 0x55, 0xb2, 0x40, 0xfb, 0xcf, 0xe0, 0x48, 0x79, 0xb7, 0x30, 0x21, 0xc2, 0x61, 0x5c, 0xbd,
	0xdb, 0xc2, 0xf2, 0x4c, 0xa7, 0xa6, 0xd5, 0xa7, 0x65, 0x0b, 0x2b, 0x80, 0x02, 0x8e, 0x83, 0x9f,
	0xa3, 0x9e, 0x4b, 0xda, 0x59, 0xee, 0x48, 0x7e, 0x17, 0x26, 0xa3, 0xc4, 0xa1, 0xf8, 0x33, 0x90,
	0x3a, 0x38, 0x65, 0x94, 0xa8, 0xca, 0xdd, 0x19, 0xf0, 0x03, 0xce, 0x41, 0xcf, 0xea, 0x27, 0x1a,
	0xa7, 0x45, 0x9d, 0xfd, 0x27, 0x12, 0xbe, 0x8d, 0xd3, 0xed, 0x15, 0x9e, 0xcb, 0x3f, 0xc3, 0xe2,
	0xe7, 0xa0, 0xf1, 0x13, 0xb8, 0x0b, 0x93, 0x60, 0x0d, 0xef, 0x2e, 0x5f, 0xaf, 0xfd, 0xde, 0x47,
	0xbf, 0x3d, 0x5e, 0xd2, 0xee, 0x6f, 0x9d, 0xdb, 0xba, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xca,
	0x34, 0xb1, 0x30, 0x3b, 0x01, 0x00, 0x00,
}
