// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2c.proto

package Protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2CSendRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2CSendRequest) Reset()         { *m = C2CSendRequest{} }
func (m *C2CSendRequest) String() string { return proto.CompactTextString(m) }
func (*C2CSendRequest) ProtoMessage()    {}
func (*C2CSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fff5227ba7e53484, []int{0}
}

func (m *C2CSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2CSendRequest.Unmarshal(m, b)
}
func (m *C2CSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2CSendRequest.Marshal(b, m, deterministic)
}
func (m *C2CSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2CSendRequest.Merge(m, src)
}
func (m *C2CSendRequest) XXX_Size() int {
	return xxx_messageInfo_C2CSendRequest.Size(m)
}
func (m *C2CSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C2CSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C2CSendRequest proto.InternalMessageInfo

func (m *C2CSendRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *C2CSendRequest) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *C2CSendRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type C2CSendResponse struct {
	Msgid                int64    `protobuf:"varint,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2CSendResponse) Reset()         { *m = C2CSendResponse{} }
func (m *C2CSendResponse) String() string { return proto.CompactTextString(m) }
func (*C2CSendResponse) ProtoMessage()    {}
func (*C2CSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fff5227ba7e53484, []int{1}
}

func (m *C2CSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2CSendResponse.Unmarshal(m, b)
}
func (m *C2CSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2CSendResponse.Marshal(b, m, deterministic)
}
func (m *C2CSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2CSendResponse.Merge(m, src)
}
func (m *C2CSendResponse) XXX_Size() int {
	return xxx_messageInfo_C2CSendResponse.Size(m)
}
func (m *C2CSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_C2CSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_C2CSendResponse proto.InternalMessageInfo

func (m *C2CSendResponse) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *C2CSendResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type C2CPushRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Msgid                int64    `protobuf:"varint,3,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2CPushRequest) Reset()         { *m = C2CPushRequest{} }
func (m *C2CPushRequest) String() string { return proto.CompactTextString(m) }
func (*C2CPushRequest) ProtoMessage()    {}
func (*C2CPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fff5227ba7e53484, []int{2}
}

func (m *C2CPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2CPushRequest.Unmarshal(m, b)
}
func (m *C2CPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2CPushRequest.Marshal(b, m, deterministic)
}
func (m *C2CPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2CPushRequest.Merge(m, src)
}
func (m *C2CPushRequest) XXX_Size() int {
	return xxx_messageInfo_C2CPushRequest.Size(m)
}
func (m *C2CPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C2CPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C2CPushRequest proto.InternalMessageInfo

func (m *C2CPushRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *C2CPushRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *C2CPushRequest) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *C2CPushRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type C2CPushResponse struct {
	Msgid                int64    `protobuf:"varint,1,opt,name=msgid,proto3" json:"msgid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2CPushResponse) Reset()         { *m = C2CPushResponse{} }
func (m *C2CPushResponse) String() string { return proto.CompactTextString(m) }
func (*C2CPushResponse) ProtoMessage()    {}
func (*C2CPushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fff5227ba7e53484, []int{3}
}

func (m *C2CPushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2CPushResponse.Unmarshal(m, b)
}
func (m *C2CPushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2CPushResponse.Marshal(b, m, deterministic)
}
func (m *C2CPushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2CPushResponse.Merge(m, src)
}
func (m *C2CPushResponse) XXX_Size() int {
	return xxx_messageInfo_C2CPushResponse.Size(m)
}
func (m *C2CPushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_C2CPushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_C2CPushResponse proto.InternalMessageInfo

func (m *C2CPushResponse) GetMsgid() int64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func init() {
	proto.RegisterType((*C2CSendRequest)(nil), "Protocol.C2CSendRequest")
	proto.RegisterType((*C2CSendResponse)(nil), "Protocol.C2CSendResponse")
	proto.RegisterType((*C2CPushRequest)(nil), "Protocol.C2CPushRequest")
	proto.RegisterType((*C2CPushResponse)(nil), "Protocol.C2CPushResponse")
}

func init() { proto.RegisterFile("c2c.proto", fileDescriptor_fff5227ba7e53484) }

var fileDescriptor_fff5227ba7e53484 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x36, 0x4a, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x08, 0x00, 0x51, 0xc9, 0xf9, 0x39, 0x4a, 0x7e, 0x5c,
	0x7c, 0xce, 0x46, 0xce, 0xc1, 0xa9, 0x79, 0x29, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x42, 0x5c, 0x2c, 0x69, 0x45, 0xf9, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0xb6,
	0x10, 0x1f, 0x17, 0x53, 0x49, 0xbe, 0x04, 0x13, 0x58, 0x84, 0xa9, 0x24, 0x5f, 0x48, 0x82, 0x8b,
	0x3d, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6,
	0x55, 0x72, 0xe5, 0xe2, 0x87, 0x9b, 0x57, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc2, 0xc5,
	0x9a, 0x5b, 0x9c, 0x9e, 0x99, 0x02, 0x35, 0x11, 0xc2, 0x11, 0x92, 0xe1, 0xe2, 0x2c, 0xc9, 0xcc,
	0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0x80, 0x9a, 0x8c, 0x10, 0x50, 0x2a, 0x02, 0x3b, 0x2b, 0xa0,
	0xb4, 0x38, 0x03, 0x9f, 0xb3, 0x90, 0x9c, 0xc1, 0x84, 0xe2, 0x0c, 0x84, 0x9d, 0xcc, 0x38, 0xed,
	0x64, 0x41, 0xb7, 0x53, 0x1d, 0xec, 0x74, 0x88, 0x9d, 0xf8, 0x9c, 0x9e, 0xc4, 0x06, 0x0e, 0x44,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xfc, 0x6c, 0x4b, 0x51, 0x01, 0x00, 0x00,
}
